window.LANG_LIST = [
    { code: 'zh-CN', name: '简体中文' },
    { code: 'zh-TW', name: '繁體中文' },
    { code: 'en', name: 'English' }
];

window.TRANSLATIONS = {
    'en': {
        'nav.home': 'Home',
        'nav.season': 'Annual Rankings',
        'nav.active': 'Last 3 Years Rankings',
        'nav.region': 'Regional Rankings',
        'nav.comprehensive': 'Comprehensive Rankings',
        'nav.record': 'Regional Records',
        'season.title': 'Annual Rankings',
        'season.subtitle': 'This page shows annual rankings, taking one calendar year as a cycle (e.g., 2026 season). It ranks players\' best results achieved within that year. All ranking results are from official WCA competitions.',
        'active.title': 'Last 3 Years Rankings',
        'active.subtitle': 'This page shows rankings based on the best results achieved in the last three years. Players with no competition records for more than three years are not included. All ranking results are from official WCA competitions.',
        'region.title': 'Regional Rankings',
        'region.subtitle': 'This page shows rankings of Chinese players within their provinces/cities. For players who did not select their region on Cubing China before May 2018, they are automatically assigned to the fictional "Shenshou Valley" (see homepage announcement for details). Note: Players can now submit information change requests via the feedback page. All ranking results are from official WCA competitions.',
        'comprehensive.title': 'Comprehensive Rankings',
        'comprehensive.subtitle': 'This page calculates the sum of ranks across multiple events and ranks players accordingly.',
        'record.title': 'Regional Records',
        'record.subtitle': 'This page shows records for all provinces and cities in China across all WCA events. All results are from official WCA rankings.',
        'filter.region': 'Region',
        'filter.project': 'Event',
        'filter.gender': 'Gender',
        'filter.period': 'Period',
        'filter.province': 'Province',
        'filter.city': 'City',
        'filter.source': 'Ranking Type',
        'filter.dataset': 'Sub-dataset',
        'gender.all': 'All',
        'gender.male': 'Male',
        'gender.female': 'Female',
        'gender.unknown': 'Unknown',
        'btn.single': 'Single',
        'btn.average': 'Average',
        'btn.refresh': 'Refresh',
        'table.rank': 'Rank',
        'table.name': 'Name',
        'table.country': 'Country',
        'table.province': 'Province',
        'table.city': 'City',
        'table.result': 'Result',
        'table.competition': 'Competition',
        'table.wcaid': 'WCA ID',
        'table.event': 'Event',
        'table.events_count': 'Events',
        'table.total_rank': 'Total Rank',
        'current.single': 'Single',
        'current.average': 'Average',
        'current.historical': 'All',
        'current.season': 'Annual',
        'current.active': 'Last 3 Years',
        'current.region': 'Regional',
        'loading': 'Loading',
        'loading_failed': 'Data loading failed',
        'no_data': 'No data',
        'all_cities': 'All cities in province',
        'record.no_record': 'No record',
        'comp.select_events': 'Select events (click to choose)',
        'comp.calculating': 'Calculating comprehensive rankings, please wait...',
        'comp.current': '{source} - {count} event(s) selected ({type})',
        'announcement.launch.title': 'Website Launch',
        'announcement.launch.content': 'XCUBING website is now online. It provides annual rankings, last 3 years rankings, regional rankings, comprehensive rankings, and regional records from WCA events. We welcome all cubers to experience the site and provide feedback on any issues or suggestions. If you encounter any errors, please contact the author at: xcubing@qq.com.',
    'world': 'World',
    'continent.asia': 'Asia',
    'continent.europe': 'Europe',
    'continent.north_america': 'North America',
    'continent.south_america': 'South America',
    'continent.africa': 'Africa',
    'continent.oceania': 'Oceania',
        'project.333': '3x3x3 Cube',
        'project.222': '2x2x2 Cube',
        'project.444': '4x4x4 Cube',
        'project.555': '5x5x5 Cube',
        'project.666': '6x6x6 Cube',
        'project.777': '7x7x7 Cube',
        'project.333bf': '3x3x3 Blindfolded',
        'project.333fm': '3x3x3 Fewest Moves',
        'project.333oh': '3x3x3 One-Handed',
        'project.clock': 'Clock',
        'project.minx': 'Megaminx',
        'project.pyram': 'Pyraminx',
        'project.skewb': 'Skewb',
        'project.sq1': 'Square-1',
        'project.444bf': '4x4x4 Blindfolded',
        'project.555bf': '5x5x5 Blindfolded',
        'project.333mbf': '3x3x3 Multi-Blind',
    },

    'zh-CN': {
        'nav.home': '首页',
        'nav.season': '年度排名',
        'nav.active': '近三年度排名',
        'nav.region': '省市排名',
        'nav.comprehensive': '综合排名',
        'nav.record': '省市纪录',
        'season.title': '年度排名',
        'season.subtitle': '本页面为年度排名，以一个自然年为一个年度（如2026年即为2026年度），将参赛选手在这个年度内取得的最佳成绩进行排名。所有的排名成绩源自WCA赛事的官方排名。',
        'active.title': '近三年度排名',
        'active.subtitle': '本页面为近三年度排名，将参赛选手在最近三年内取得的最佳成绩进行排名，超过三年无参赛记录的选手不被列入排名。所有的排名成绩源自WCA赛事的官方排名。',
        'region.title': '省市排名',
        'region.subtitle': '本页面为省市排名，可以查看中国选手在其所属城市的排名，对于截至2018年5月前没有在粗饼网选择归属地的选手，系统将自动将其归入本站虚构的秘境——神手谷（具体缘由详见首页公告）。温馨提示：选手现可进入反馈页提交信息更改申请。所有的排名成绩源自WCA赛事的官方排名。',
        'comprehensive.title': '综合排名',
        'comprehensive.subtitle': '本页面为综合排名，可计算选手在多个项目的排名总和并进行排名。',
        'record.title': '省市纪录',
        'record.subtitle': '本页面为省市纪录，可以查看中国所有有参赛选手的省份及城市在WCA所有项目的纪录。所有的成绩源自WCA官方排名。',
        'filter.region': '地区',
        'filter.project': '项目',
        'filter.gender': '性别',
        'filter.period': '时期',
        'filter.province': '省份',
        'filter.city': '城市',
        'filter.source': '排名类型',
        'filter.dataset': '时期',
        'gender.all': '所有',
        'gender.male': '男',
        'gender.female': '女',
        'gender.unknown': '未知',
        'btn.single': '单次',
        'btn.average': '平均',
        'btn.refresh': '刷新',
        'table.rank': '排名',
        'table.name': '姓名',
        'table.country': '国家',
        'table.province': '省份',
        'table.city': '城市',
        'table.result': '成绩',
        'table.competition': '比赛',
        'table.wcaid': 'WCA ID',
        'table.event': '项目',
        'table.events_count': '参与项目数',
        'table.total_rank': '排名总和',
        'current.single': '单次',
        'current.average': '平均',
        'current.historical': '所有',
        'current.season': '年度',
        'current.active': '近三年度',
        'current.region': '省市',
        'loading': '加载中',
        'loading_failed': '数据加载失败',
        'no_data': '暂无数据',
        'all_cities': '全省',
        'record.no_record': '暂无纪录',
        'comp.select_events': '项目(点击选择)',
        'comp.calculating': '正在计算综合排名，请稍候...',
        'comp.current': '{source} - 已选{count}个项目 ({type})',
        'announcement.launch.title': '网站上线',
        'announcement.launch.content': 'XCUBING网站正式上线运行，网站目前提供WCA赛事的年度、近三年度、省市、综合排名及省市纪录功能，诚挚欢迎广大魔友积极体验并对网站在页面显示、功能使用等方面存在的问题和不足提出宝贵意见和建议。如您在访问网站过程中发现任何错误、故障，请及时通过以下方式反馈：作者邮箱：xcubing@qq.com。',
    'world': '世界',
    'continent.asia': '亚洲',
    'continent.europe': '欧洲',
    'continent.north_america': '北美洲',
    'continent.south_america': '南美洲',
    'continent.africa': '非洲',
    'continent.oceania': '大洋洲',

        'project.333': '三阶',
        'project.222': '二阶',
        'project.444': '四阶',
        'project.555': '五阶',
        'project.666': '六阶',
        'project.777': '七阶',
        'project.333bf': '三盲',
        'project.333fm': '最少步',
        'project.333oh': '单手',
        'project.clock': '魔表',
        'project.minx': '五魔方',
        'project.pyram': '金字塔',
        'project.skewb': '斜转',
        'project.sq1': 'SQ1',
        'project.444bf': '四盲',
        'project.555bf': '五盲',
        'project.333mbf': '多盲',
    },

    'zh-TW': {
        'nav.home': '首頁',
        'nav.season': '年度排名',
        'nav.active': '近三年度排名',
        'nav.region': '省市排名',
        'nav.comprehensive': '綜合排名',
        'nav.record': '省市紀錄',
        'season.title': '年度排名',
        'season.subtitle': '本頁面為年度排名，以一個自然年為一個年度（如2026年即为2026年度），將參賽選手在這個年度內取得的最佳成績進行排名。所有的排名成績源自WCA賽事的官方排名。',
        'active.title': '近三年度排名',
        'active.subtitle': '本頁面為近三年度排名，將參賽選手在最近三年內取得的最佳成績進行排名，超過三年無參賽記錄的選手不被列入排名。所有的排名成績源自WCA賽事的官方排名。',
        'region.title': '省市排名',
        'region.subtitle': '本頁面為省市排名，可以查看中國選手在其所屬城市的排名，對於截至2018年5月前沒有在粗餅網選擇歸屬地的選手，系統將自動將其歸入本站虛構的秘境——神手谷（具體緣由詳見首頁公告）。溫馨提示：選手現可進入反饋頁提交信息更改申請。所有的排名成績源自WCA賽事的官方排名。',
        'comprehensive.title': '綜合排名',
        'comprehensive.subtitle': '本頁面為綜合排名，可計算選手在多個項目的排名總和並進行排名。',
        'record.title': '省市紀錄',
        'record.subtitle': '本頁面為省市紀錄，可以查看中國所有有參賽選手的省份及城市在WCA所有項目的紀錄。所有的成績源自WCA官方排名。',
        'filter.region': '地區',
        'filter.project': '項目',
        'filter.gender': '性別',
        'filter.period': '時期',
        'filter.province': '省份',
        'filter.city': '城市',
        'filter.source': '排名類型',
        'filter.dataset': '時期',
        'gender.all': '所有',
        'gender.male': '男',
        'gender.female': '女',
        'gender.unknown': '未知',
        'btn.single': '單次',
        'btn.average': '平均',
        'btn.refresh': '重新整理',
        'table.rank': '排名',
        'table.name': '姓名',
        'table.country': '國家',
        'table.province': '省份',
        'table.city': '城市',
        'table.result': '成績',
        'table.competition': '比賽',
        'table.wcaid': 'WCA ID',
        'table.event': '項目',
        'table.events_count': '參與項目數',
        'table.total_rank': '排名總和',
        'current.single': '單次',
        'current.average': '平均',
        'current.historical': '所有',
        'current.season': '年度',
        'current.active': '近三年度',
        'current.region': '省市',
        'loading': '載入中',
        'loading_failed': '資料載入失敗',
        'no_data': '暫無資料',
        'all_cities': '全省',
        'record.no_record': '暫無紀錄',
        'comp.select_events': '項目(點擊選擇)',
        'comp.calculating': '正在計算綜合排名，請稍候...',
        'comp.current': '{source} - 已選{count}個項目 ({type})',
        'announcement.launch.title': '網站上線',
        'announcement.launch.content': 'XCUBING網站正式上線運行，網站目前提供WCA賽事的年度、近三年度、省市、綜合排名及省市紀錄功能，誠摯歡迎廣大魔友積極體驗並對網站在頁面顯示、功能使用等方面存在的問題和不足提出寶貴意見和建議。如您在訪問網站過程中發現任何錯誤、故障，請及時通過以下方式反饋：作者郵箱：xcubing@qq.com。',
    'world': '世界',
    'continent.asia': '亞洲',
    'continent.europe': '歐洲',
    'continent.north_america': '北美洲',
    'continent.south_america': '南美洲',
    'continent.africa': '非洲',
    'continent.oceania': '大洋洲',


        'project.333': '三階',
        'project.222': '二階',
        'project.444': '四階',
        'project.555': '五階',
        'project.666': '六階',
        'project.777': '七階',
        'project.333bf': '三盲',
        'project.333fm': '最少步',
        'project.333oh': '單手',
        'project.clock': '魔錶',
        'project.minx': '五魔方',
        'project.pyram': '金字塔',
        'project.skewb': '斜轉',
        'project.sq1': 'SQ1',
        'project.444bf': '四盲',
        'project.555bf': '五盲',
        'project.333mbf': '多盲',
    },

    'ca': {}, 'cs': {}, 'da': {}, 'de': {}, 'eo': {}, 'es-ES': {}, 'es-419': {}, 'eu': {}, 'fi': {}, 'fr': {}, 'fr-CA': {}, 'hr': {}, 'hu': {}, 'id': {}, 'it': {}, 'ja': {}, 'kk': {}, 'ko': {}, 'nl': {}, 'pl': {}, 'pt-PT': {}, 'pt-BR': {}, 'ro': {}, 'ru': {}, 'sk': {}, 'sl': {}, 'sv': {}, 'th': {}, 'uk': {}, 'vi': {}
};

window.__ = function(key, params = {}) {
    const lang = state.currentLang;
    const translations = TRANSLATIONS[lang] || TRANSLATIONS['en'] || {};
    let text = translations[key];
    if (text === undefined) {
        text = TRANSLATIONS['en']?.[key] || key;
    }
    if (params) {
        for (let [k, v] of Object.entries(params)) {
            text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
        }
    }
    return text;
};